#!/bin/env bash
need() {
    if ! command -v "$1" &>/dev/null; then
        if command -v pacman &>/dev/null; then
            sudo pacman -Sy --needed --noconfirm "$1"
        else
            echo "install $1 with your distro pkgmanager"
        fi
    fi
}
need curl
need git
git clone https://github.com/X3ric/xtool
cd xtool
chmod +x "./xtool"
if [[ ":$PATH:" == *":$HOME/.local/bin:"* ]]; then
    cp "./xtool" "$HOME/.local/bin"
else
    sudo cp "./xtool" "/usr/bin"
fi 
cd ..
rm -rf xtool